server:
  port: 7999

spring:
  profiles:
    include: secret

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/sbb?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: sbsst
    password: sbs123414
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

cloud:
  aws:
    s3:
      bucket: jong-first-bucket
    credentials:
      access-key: AKIA6N2FHP6STLDOF4MV #IAM 계정 - access key
      secret-key: 3FGOEKQ3QEj53zBXFNh5IzDzNs3EWYcoT/AwG0In #IAM 계정 - secret access key
    region:
      static: ap-northeast-2 #현재 s3 버킷의 Region
    stack:
      auto: false